version: "3.9"

services:
  loadbalancer:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - swoole-network
  app:
    build:
      context: .
    ports:
      - "9501:9501"
    volumes:
      - .:/var/www
    networks:
      - swoole-network
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - swoole-network

networks:
  swoole-network:
    driver: bridge